examples/haitham_work_area/genz_33_reversal_filter.py

Genz-33:reversal completed

---

examples/atyab_work_area/oop/contact_mgmt_app/contact_book.py
examples/atyab_work_area/oop/contact_mgmt_app/contact_record.py
examples/atyab_work_area/oop/contact_mgmt_app/data/contact_store.json
examples/atyab_work_area/oop/contact_mgmt_app/main_app.py

Redesigning the contact book management system using OOP paradigm.

GenZ-50: [OOP] Contact Book Management System

---

examples/atyab_work_area/decorator_prac.py

Added example of the usage of decorator in Python

GenZ-55: Generators in Python

---

PULL_REQUEST_TEMPLATE.md
README.md
main_app.py
my_per_notes.txt
src/controllers/todo_record_controller.py
static/index.html

This PR creates an an empty todo list project with dependencies. So the team can use it as an initial reference.
https://trello.com/c/PxJ8kNBz/34-setup-an-empty-todo-list-project-with-dependencies
Goto the directory where the main_app.py file is located and run "pip install -r requirements.txt"
Then, run python main_app.py
Test the API endpoint /api/v1/todoRecords by sending GET, PUT, POST and DELETE request from POSTMAN
Revert this PR
None

GenZ-34: Setup an empty todo list project with dependencies.

---

examples/lujain_work_area/Contact_Book_OOP/contact_book_api.py

This pull request adds an API for a Contact Book Management System implemented using CherryPy. The API provides endpoints for adding, deleting, updating, and searching contacts. It allows external applications to programmatically manage contacts efficiently and securely.
This pull request addresses the following user story: https://trello.com/c/6qdrKnr8
1. Deploy the CherryPy application.
2. Send HTTP requests to the API endpoints using tools like Postman or curl.
3. Test each endpoint using the provided instructions.
- Add Contact: Send a POST request to `/add_contact` with the contact details in the request body.
- Delete Contact: Send a DELETE request to `/delete_contact/{contactId}` with the contact ID.
- Update Contact: Send a PUT request to `/update_contact/{contactId}` with the …

genzsprfour-32: Conatct_Book_Management_System_API

---

data/readme.txt
src/controllers/todo_record_controller.py
src/models/todolist.py
src/services/todo_list_services.py

Fixed imports, relative directory and logcal error with write.
Figure out by the branch id
Run the application and send any request. It should not respond with 500
Revert the PR

GenZ-4-36: Fix imports in todo list service.

---

src/models/item.py
src/models/test/test_item.py

test_item_todolist

---

examples/sara_work_area/Contact_Book_API/cbms/contact_book.py
examples/sara_work_area/Contact_Book_API/cbms/contact_book_service.py
examples/sara_work_area/Contact_Book_API/cbms/contact_record.py
examples/sara_work_area/Contact_Book_API/cbms/data/data_store.json
examples/sara_work_area/Contact_Book_API/contact_api.py
examples/sara_work_area/Contact_Book_API/controller/contact_records_controller.py
examples/sara_work_area/Contact_Book_API/model/contact_record.py

GenZ-Spr_Four: Logic for Contact Book API

---

examples/Sughiyas_work_area/OOP_Contact_Book/api_contact.py

API Contact Book

---

src/controllers/todo_record_controller.py

GenZ-4-4: RESTful API Endpoint for TODO List Item Retrieval

---

src/controllers/todo_record_controller.py

added bug fixes for get

---

examples/haitham_work_area/genz_sprthree_12_oop_contact_book/api_server.py
examples/haitham_work_area/genz_sprthree_12_oop_contact_book/txt_contact_book.py

OOP Contact Book API 

---

examples/abdul_aziz_work_area/oop_contact_book/contactbookapi.py
examples/abdul_aziz_work_area/oop_contact_book/testing.py

work in progress contack book api/ pushing changes to continue working in it later 

---

main_app.py
static/index.html

GenZ-4-40: Fixed JS to use the server address instead of localhost

---

examples/lujain_work_area/ToDo_Delete/Item.py
examples/lujain_work_area/ToDo_Delete/TodoList.py
examples/lujain_work_area/ToDo_Delete/load_todo_list.py
examples/lujain_work_area/ToDo_Delete/to_do_list_delete_item.py
examples/lujain_work_area/contact_book_management_system_api/contact_book_api.py
src/controllers/todo_record_controller.py

#genzsprfour-7: RESTful API Endpoint for TODO List Item Deletion

---

examples/abbas_work_area/multithreading.py

Threading in Python

---

examples/haitham_work_area/genz_86ep9jddd_threading.py

python threading

---

examples/abdul_aziz_work_area/thread_test.py

86ep9jphf. added threading test file

---

examples/sara_work_area/multi_threading.py
examples/sara_work_area/threading_python.py

Ticket 86ep9k4kw: Threading

---

examples/sara_work_area/resume/resume_parser.py

Feature: Implemented a basic example to test resume parser

---

examples/lujain_work_area/threading/threading_example.py

This pull request provides an example of threading in Python. The code demonstrates how to use the threading module to execute tasks concurrently without altering the functionality.
https://app.clickup.com/t/86ep9jhgg
1. Clone the repository.
2. Navigate to the directory containing the Python file.
3. Run the Python script.
4. Observe the output of the program.
5. Ensure that the random numbers are printed and the countdown timer works as expected.
6. Verify that the final message "Threads have finished executing." is printed after both tasks complete.
To revert this change:
- Restore the original code with the `import random` and `import time` statements.
- Ensure that `random.randint()` and `time.sleep()` are correctly used within their respective functions.
None.

86ep9jhgg: Threading Example

---

examples/Sughiyas_work_area/directory_monitor/directory_event.py

Directory monitor and event based file handler

---

examples/abbas_work_area/check_thread.py
examples/abbas_work_area/data/data.json

86epb0vee: Directory monitor and event based file handler

---

examples/abbas_work_area/multi_processing.py

86epbe4x6: Parallel Programming in Python

---

examples/haitham_work_area/genz_86epb0kwg/genz_86epb0kwg_dirmonitoring.py

DIR Monitoring and event based file handler

---

examples/lujain_work_area/directory_monitor/directory_monitor.py

This pull request adds functionality to monitor a directory for newly uploaded files, process them, and save the processed content to a log file. It includes the following changes:
- Added a function to process uploaded files.
- Implemented a file system event handler using Watchdog to monitor file creation events.
- Created a main thread to save processed results to a log file.
- Configured logging to save messages to a file named "processing_log.txt".
- Added comments to explain each part of the code and the role of Watchdog.
https://app.clickup.com/t/86epb0muw
1. Deploy the code to the desired environment (local, stage, production).
2. Run the script with Python, providing a directory to monitor as a command-line argument.
3. Create new files in the monitored directory and observe the …

Directory monitor

---

examples/sara_work_area/multi_threading/directory_monitor.py

86epb0mr4: Added logic for monitoring the directory

---

examples/atyab_work_area/multi_threading/rank_cv.py

Provided the example of multithreading in Python along with passing arguments to async functions.
https://app.clickup.com/t/86ep7crge

86ep7crge: Threading in Python

---

examples/abdul_aziz_work_area/dir_moni/Directory_monitor.py
examples/abdul_aziz_work_area/dir_moni/watched_directory/text_test3

added files and logic for dir_mon

---

examples/atyab_work_area/producer_consumer_arch/cv_processor.py

86epdr2zu: Discuss Producer Consumer Architecture

---

examples/sara_work_area/cv_processing.py

Ticket 86epeyrhw: Added Logic for CV Processing

---

examples/atyab_work_area/async_func/test.py
examples/atyab_work_area/async_func/test2.py
examples/atyab_work_area/async_func/test3.py
examples/atyab_work_area/async_func/test4.py

86ep7cvnb: Introduction to Asyncio

---

examples/lujain_work_area/Resume_Processer/consumer.py
examples/lujain_work_area/Resume_Processer/main.py
examples/lujain_work_area/Resume_Processer/producer.py
examples/lujain_work_area/Resume_Processer/result_monitor.py

Summary of Change
This PR implements an application that utilizes Pyresparser and Python's multiprocessing to efficiently process CV files. The application leverages 8 CPU cores, with 1 core for the producer process, 6 cores for the consumer processes, and 1 core for processing results and writing JSON result files.
Key Features:
Producer Process: Monitors a directory for new CV files and places them into a processing queue.
Consumer Processes: Processes CV files from the queue using Pyresparser and places the results into a result queue.
Result Monitor Process: Creates separate JSON files for each processed result, ensuring unique filenames for files with the same name but different content.
This setup ensures efficient utilization of CPU cores and proper handling of CV files.
Link to …

Added CV Processor module

---

examples/abbas_work_area/check_thread - Copy.py
examples/abbas_work_area/cv_consumer.py
examples/abbas_work_area/cv_processor.py

86epez07f: CV Processing Application with Pyresparser and Multiprocessing

---

examples/Rudaina_work_area/cv_processing/process_cv_files.py

86epeykrb: CV Processing Application

---

examples/haitham_work_area/genz_86epeytn8_cv_processing.py

Feature: CV Processor

---

examples/atyab_work_area/welcome_api/Dockerfile
examples/atyab_work_area/welcome_api/main_api.py

86epdrpmn : Instructions to create a Docker Image 
